remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
title: "A Quantification of Metagame Shifts in Professional League of Legends Gameplay"
description: "Predicting game patch versions from draft picks and team compositions from 10 years of professional play"
